name: Comment
on: 
  issues:
    types: [opened, edited]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: gh issue comment "${{ github.event.issue.number }}" --body "Hello, ${GITHUB_ACTOR}"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHubトークン